### ISSUE TITLE
crash on partially pushed images

### ISSUE THREAD

**Issue by so0k** [vivekjuneja/docker_registry_cli#4]
registry api returns 404 when requesting tag list of partially fulled images, the script errors out.

```
/usr/src/app # python browser.py user:pw@registry.mysite.com list all
Traceback (most recent call last):
  File "browser.py", line 196, in <module>
    search_results = get_all_repo_dict(regurl, all_repos, auth_flag, ssl_flag)
  File "browser.py", line 118, in get_all_repo_dict
    parsed_repo_tag_req_resp = get_tags_for_repo(url, repo, auth, ssl)
  File "browser.py", line 109, in get_tags_for_repo
    return parsed_repo_tag_req_resp["tags"]
KeyError: 'tags'
```

**Comment by vivekjuneja** [comment]
Can you please share the response for the following  -

1. curl -u username:password http://<endpoint>:<port>/v2/tags

**Comment by vivekjuneja** [comment]
Unfortunately, I do not have "verbose" mode yet. I will work on that to help debugging.

I saw you raised this with the Docker Distribution https://github.com/docker/distribution/issues/777 

I think we need better error handling to alleviate this issue.

Thanks @so0k again for the finding.
